name: vilius-image-publish
on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: docker.io/papavilius
  IMAGE_NAME: api-demo
  IMAGE_TAG: ${{ github.run_number }}


jobs:

  api-image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint with Black
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }} latest
          containerfiles: |
            ./Containerfile

      - name: Push To ${{ env.REGISTRY }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }} latest
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
